version: '3'
services:
  database:
    build: ./database
    restart: always
  backend:
    build: ./backend
    restart: always
    depends_on:
      - database
    ports:
      - 0.0.0.0:9447:9447
    environment:
      - PROD=1
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    environment:
      - PROD=1
    ports:
      - 0.0.0.0:8080:8080