version: '3'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 0.0.0.0:9447:9447
    enviornment:
      - BACKEND_URL="backend.hal-3900.ml"
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 0.0.0.0:8080:8080